// healthPreferences.js
export default [
  'alcohol-cocktail',
  'alcohol-free',
  'crustacean-free',
  'dairy-free',
  'immuno-supportive',
  'DASH',
  'egg-free',
  'fish-free',
  'fodmap-free',
  'gluten-free',
  'keto-friendly',
  'kidney-friendly',
  'low-potassium',
  'low-sugar',
  'Mediterranean',
  'shellfish-free',
  'soy-free',
  'sugar-conscious',
  'sulfite-free',
  'tree-nut-free',
  'vegan',
  'vegetarian',
  'wheat-free',
]
